export MANGO_DOTFILES_DIR="${HOME}/github/dotfiles"
export MANGO_TOOLS_DIR="${HOME}/tools"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${MANGO_TOOLS_DIR}/brew/bin:${PATH}"
export PATH="${MANGO_TOOLS_DIR}/google-cloud-sdk/bin:${PATH}"
export PATH="${MANGO_TOOLS_DIR}/Go/bin:${PATH}"

export PAGER="less -F -X"

# Things that are still in private depot.
export PATH="${HOME}/depot/tools/scripts:${PATH}"
export GOPATH="${HOME}/tools/Go:${HOME}/depot/website"

# Python
export PATH="${MANGO_TOOLS_DIR}/pyenv/bin:${PATH}"
export PYENV_ROOT="${MANGO_TOOLS_DIR}/pyenv"
if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init - zsh)"
fi

# Ruby
# Install using `gem install --user-install <name>`
if command -v rbenv >/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi
export GEM_HOME="${MANGO_TOOLS_DIR}/gem"
export PATH="$GEM_HOME/bin:${PATH}"

# Prompt
export STARSHIP_CONFIG="$MANGO_DOTFILES_DIR/shell/startship.toml"
eval "$(starship init zsh)"

# zsh plugins
# To install: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
source "${HOME}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Claude settings
if [[ ! -e "${HOME}/.claude/settings.json" ]]; then
  mkdir -p "${HOME}/.claude"
  ln -s "${MANGO_DOTFILES_DIR}/claude/settings.json" "${HOME}/.claude/settings.json"
fi
