export MANGO_DOTFILES_DIR="${HOME}/github/dotfiles"
export MANGO_TOOLS_DIR="${HOME}/tools"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="${MANGO_TOOLS_DIR}/brew/bin:${PATH}"
export PATH="${MANGO_TOOLS_DIR}/google-cloud-sdk/bin:${PATH}"
export PATH="${MANGO_TOOLS_DIR}/Go/bin:${PATH}"

export PAGER="less -F -X"

# Things that are still in private depot.
export PATH="${HOME}/depot/tools/scripts:${PATH}"
export GOPATH="${HOME}/tools/Go:${HOME}/depot/website"

# Python
export PATH="${MANGO_TOOLS_DIR}/pyenv/bin:${PATH}"
export PYENV_ROOT="${MANGO_TOOLS_DIR}/pyenv"
eval "$(pyenv init - zsh)"

# Ruby
# Install using `gem install --user-install <name>`
export GEM_HOME="${MANGO_TOOLS_DIR}/gem"
export PATH="$GEM_HOME/bin:${PATH}"

# Prompt
export STARSHIP_CONFIG="$MANGO_DOTFILES_DIR/shell/startship.toml"
eval "$(starship init zsh)"

# zsh plugins
# To install: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
source "${HOME}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
